apiVersion: v2
description: Inbucket is an email testing application
name: inbucket
type: application
appVersion: 3.0.0
version: 2.0.0
keywords:
  - inbucket
  - mail
  - smtp
  - pop3
  - email
  - testing
  - disposable webmail
home: https://www.inbucket.org/
sources:
  - https://github.com/inbucket/inbucket
maintainers:
  - name: cpanato
    email: ctadeu@gmail.com

annotations:
  artifacthub.io/license: MIT
