image:
  repository: inbucket/inbucket
  tag: 3.0.0@sha256:1f10a0efea694592c06799c729aee1d6d71c9a4f72b73031d4a426ef5f26dfc1
  pullPolicy: Always

service:
  annotations: {}
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP
  portName:
    http: http
    smtp: smtp
    pop3: pop3
  port:
    http: 9000
    smtp: 2500
    pop3: 1100
  nodePort:
    http: ""
    smtp: ""
    pop3: ""

inbucket:
  smtp:
    tls:
      secretName: ""

extraEnv:
  INBUCKET_LOGLEVEL: "info"
  INBUCKET_MAILBOXNAMING: "local"
  INBUCKET_SMTP_ADDR: "0.0.0.0:2500"
  INBUCKET_SMTP_DOMAIN: "inbucket"
  INBUCKET_SMTP_MAXRECIPIENTS: "200"
  INBUCKET_SMTP_MAXMESSAGEBYTES: "10240000"
  INBUCKET_SMTP_DEFAULTACCEPT: "true"
  INBUCKET_SMTP_ACCEPTDOMAINS: ""
  INBUCKET_SMTP_REJECTDOMAINS: ""
  INBUCKET_SMTP_DEFAULTSTORE: "true"
  INBUCKET_SMTP_STOREDOMAINS: ""
  INBUCKET_SMTP_DISCARDDOMAINS: ""
  INBUCKET_SMTP_TIMEOUT: "300s"
  INBUCKET_SMTP_TLSENABLED: "false"
  INBUCKET_SMTP_TLSPRIVKEY: "/smtp-tls-secret/cert.key"
  INBUCKET_SMTP_TLSCERT: "/smtp-tls-secret/cert.crt"
  INBUCKET_POP3_ADDR: "0.0.0.0:1100"
  INBUCKET_POP3_DOMAIN: "inbucket"
  INBUCKET_POP3_TIMEOUT: "600s"
  INBUCKET_WEB_ADDR: "0.0.0.0:9000"
  INBUCKET_WEB_BASEPATH: ""
  INBUCKET_WEB_UIDIR: "ui"
  INBUCKET_WEB_GREETINGFILE: "/config/greeting.html"
  INBUCKET_WEB_TEMPLATECACHE: "true"
  INBUCKET_WEB_MAILBOXPROMPT: "@inbucket"
  INBUCKET_WEB_COOKIEAUTHKEY: ""
  INBUCKET_WEB_MONITORVISIBLE: "true"
  INBUCKET_WEB_MONITORHISTORY: "30"
  INBUCKET_STORAGE_TYPE: "memory"
  INBUCKET_WEB_PPROF: "false"
  INBUCKET_STORAGE_PARAMS: ""
  INBUCKET_STORAGE_RETENTIONPERIOD: "24h"
  INBUCKET_STORAGE_RETENTIONSLEEP: "50ms"
  INBUCKET_STORAGE_MAILBOXMSGCAP: "500"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: inbucket.example.com
      paths:
        - path: /
          # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.)
          # pathType: Prefix

  tls: []
  #  - secretName: inbucket-example-tls
  #    hosts:
  #      - inbucket.example.com

podAnnotations: {}
resources: {}

persistence:
  enabled: false
  path: /storage
  size: 1Gi
  className:
  accessMode: ReadWriteOnce
