apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inbucket.name" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "inbucket.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{ toYaml .Values.extraEnv | indent 2 }}
