{{- $mountSmtpTlsSecret := eq (include "inbucket.mountSmtpTlsSecret" .) "true" -}}
{{- $addPersistence := eq (include "inbucket.persistenceEnabled" .) "true" -}}
{{- $addVolumes := or $addPersistence $mountSmtpTlsSecret -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "inbucket.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "inbucket.chart" . }}
  name: {{ include "inbucket.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "inbucket.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "inbucket.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "inbucket.chart" . }}
    spec:
      containers:
        - name: {{ include "inbucket.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          envFrom:
          - configMapRef:
              name: {{ include "inbucket.name" . }}-configmap
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: smtp
              containerPort: 2500
              protocol: TCP
            - name: pop3
              containerPort: 1100
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- if $addVolumes }}
          volumeMounts:
            {{- if $addPersistence }}
            - mountPath: {{ .Values.persistence.path }}
              name: {{ include "inbucket.fullname" . }}
              readOnly: false
            {{- end }}
            {{- if $mountSmtpTlsSecret }}
            - mountPath: "/smtp-tls-secret"
              name: {{ include "inbucket.smtpTlsSecret" . }}
              readOnly: true
            {{- end }}
        {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
    {{- end }}
    {{- if $addVolumes }}
      volumes:
      {{- if $addPersistence }}
        - name: {{ include "inbucket.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "inbucket.fullname" . }}
      {{- end }}
      {{- if $mountSmtpTlsSecret }}
        - name: {{ include "inbucket.smtpTlsSecret" . }}
          secret:
            secretName: {{ include "inbucket.smtpTlsSecret" . }}
      {{- end }}
    {{- end }}
